# Generated by Django 4.2.1 on 2024-06-05 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('date_found', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='found_item_images')),
            ],
            options={
                'verbose_name': 'Found Item',
                'verbose_name_plural': 'Found Items',
                'ordering': ['-date_found'],
            },
        ),
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('date_lost', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='lost_item_images')),
            ],
            options={
                'verbose_name': 'Lost Item',
                'verbose_name_plural': 'Lost Items',
                'ordering': ['-date_lost'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('course', models.CharField(max_length=100)),
                ('current_year', models.PositiveIntegerField()),
                ('current_semester', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('created', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
