# Generated by Django 4.2.1 on 2024-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
